'use client';

import React from 'react';
// Import the WMS Inventory Ledger component generated by the AI tool
import InventoryLedger from '@/components/InventoryLedger';

export default function WarehousePage() {
  return (
    <div className="p-6 bg-slate-950 min-h-screen">
      {/* Central WMS Dashboard Component containing KPI cards, Audit Trail, and Maker-Checker flows */}
      <InventoryLedger />
    </div>
  );
}